"""
Table initialization migration.

Revision ID: b7922492f289
Revises:
Create Date: 2021-01-13 18:30:50.967876
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7922492f289"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the db."""
    op.create_table(
        "movie_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("pos_per", sa.Integer(), nullable=True),
        sa.Column("neg_per", sa.Integer(), nullable=True),
        sa.Column("amount_pos_reviews", sa.Integer(), nullable=True),
        sa.Column("amount_neg_reviews", sa.Integer(), nullable=True),
        sa.Column("search_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movie_info_name"), "movie_info", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade changes in the bd."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movie_info_name"), table_name="movie_info")
    op.drop_table("movie_info")
    # ### end Alembic commands ###
